name: Android Build

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Cache Library folder
      uses: actions/cache@v4
      with:
        path: Library
        key: ${{ runner.os }}-library-${{ hashFiles('**/ProjectSettings/ProjectVersion.txt') }}

    - name: Build Android with Unity Builder
      uses: webbertakken/unity-builder@v2
      with:
        unityVersion: 2021.3.0f1
        targetPlatform: Android

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: NeonSlingshotBreaker.apk
        path: build/Android/**/*.apk
